[package]
name = "subspace-desktop"
version = "0.5.0"
description = "Subspace desktop"
authors = ["Subspace Labs <https://subspace.network>"]
license = "Apache-2.0"
repository = "https://github.com/subspace/subspace-desktop"
edition = "2021"

[build-dependencies]
substrate-build-script-utils = { version = "3.0.0", git = "https://github.com/paritytech/substrate", rev = "c364008a6c7da8456e17967f55edf51e45146998" }
tauri-build = { version = "1.0.0-rc.4", features = [] }

[dependencies]
anyhow = "1.0.44"
dotenv = "0.15.0"
event-listener-primitives = "2.0.1"
fdlimit = "0.2.1"
fs2 = "0.4.3"
hex = "0.4.3"
log = "0.4.14"
names = { version = "0.12.0", default-features = false }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", rev = "c4f3d028621edb293d2c423516221aa396f76a2d" }
sc-executor = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", rev = "c4f3d028621edb293d2c423516221aa396f76a2d", features = ["wasmtime"] }
sc-network = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", rev = "c4f3d028621edb293d2c423516221aa396f76a2d" }
sc-service = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", rev = "c4f3d028621edb293d2c423516221aa396f76a2d", features = ["wasmtime"] }
sc-tracing = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", rev = "c4f3d028621edb293d2c423516221aa396f76a2d" }
serde_json = "1.0.79"
serde = { version = "1.0.136", features = [ "derive" ] }
sp-core = { version = "6.0.0", git = "https://github.com/paritytech/substrate", rev = "c4f3d028621edb293d2c423516221aa396f76a2d" }
sp-panic-handler = { version = "4.0.0", git = "https://github.com/paritytech/substrate", rev = "c4f3d028621edb293d2c423516221aa396f76a2d" }
subspace-core-primitives = { git = "https://github.com/subspace/subspace", rev = "72b2c44971a2db1266995a8c0fe1223ef09be784" }
subspace-farmer = { git = "https://github.com/subspace/subspace", rev = "72b2c44971a2db1266995a8c0fe1223ef09be784" }
subspace-rpc-primitives = { git = "https://github.com/subspace/subspace", rev = "72b2c44971a2db1266995a8c0fe1223ef09be784" }
subspace-runtime = { git = "https://github.com/subspace/subspace", rev = "72b2c44971a2db1266995a8c0fe1223ef09be784" }
subspace-service = { git = "https://github.com/subspace/subspace", rev = "72b2c44971a2db1266995a8c0fe1223ef09be784" }
subspace-solving = { git = "https://github.com/subspace/subspace", rev = "72b2c44971a2db1266995a8c0fe1223ef09be784" }
tokio = { version = "1.11.0", features = ["macros", "rt-multi-thread"] }

[target.'cfg(windows)'.dependencies]
winreg = "0.10.1"

[dependencies.tauri]
default-features = false
# `wry` and `objc-exception` features are default, but we disable `compression` feature to avoid `zstd` crate version conflicts
features = ["api-all", "objc-exception", "system-tray", "wry"]
version = "1.0.0-rc.4"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]

[profile.dev]
opt-level = 3

[patch.crates-io]
# TODO: Remove once chacha20poly1305 0.10 appears in libp2p's dependencies
chacha20poly1305 = { git = "https://github.com/RustCrypto/AEADs", rev = "06dbfb5571687fd1bbe9d3c9b2193a1ba17f8e99" }
# TODO: Remove once https://github.com/rust-rse/reed-solomon-erasure/pull/98 is released
reed-solomon-erasure = { git = "https://github.com/nazar-pc/reed-solomon-erasure", rev = "b6596ee10904faff3b68bbb3a82faa1d8ab05a7b" }
