[package]
name = "subspace-desktop"
version = "0.4.1"
description = "Subspace desktop"
authors = ["Subspace Labs <https://subspace.network>"]
license = "Apache-2.0"
repository = "https://github.com/subspace/subspace-desktop"
edition = "2021"

[build-dependencies]
substrate-build-script-utils = { version = "3.0.0", git = "https://github.com/paritytech/substrate", rev = "c364008a6c7da8456e17967f55edf51e45146998" }
tauri-build = { version = "1.0.0-rc.4", features = [] }

[dependencies]
anyhow = "1.0.44"
dotenv = "0.15.0"
event-listener-primitives = "2.0.1"
fdlimit = "0.2.1"
fs2 = "0.4.3"
hex = "0.4.3"
jsonrpsee = { version = "0.8.0", features = ["client", "macros", "server"] }
log = "0.4.14"
names = { version = "0.12.0", default-features = false }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", rev = "c364008a6c7da8456e17967f55edf51e45146998" }
sc-executor = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", rev = "c364008a6c7da8456e17967f55edf51e45146998", features = ["wasmtime"] }
sc-network = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", rev = "c364008a6c7da8456e17967f55edf51e45146998" }
sc-service = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", rev = "c364008a6c7da8456e17967f55edf51e45146998", features = ["wasmtime"] }
sc-tracing = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", rev = "c364008a6c7da8456e17967f55edf51e45146998" }
serde_json = "1.0.79"
serde = { version = "1.0.136", features = [ "derive" ] }
sp-core = { version = "6.0.0", git = "https://github.com/paritytech/substrate", rev = "c364008a6c7da8456e17967f55edf51e45146998" }
sp-panic-handler = { version = "4.0.0", git = "https://github.com/paritytech/substrate", rev = "c364008a6c7da8456e17967f55edf51e45146998" }
subspace-core-primitives = { git = "https://github.com/subspace/subspace", rev = "46420f74bc87f38795a7a4a0196d7214f90ed929" }
subspace-farmer = { git = "https://github.com/subspace/subspace", rev = "46420f74bc87f38795a7a4a0196d7214f90ed929" }
subspace-runtime = { git = "https://github.com/subspace/subspace", rev = "46420f74bc87f38795a7a4a0196d7214f90ed929" }
subspace-service = { git = "https://github.com/subspace/subspace", rev = "46420f74bc87f38795a7a4a0196d7214f90ed929" }
subspace-solving = { git = "https://github.com/subspace/subspace", rev = "46420f74bc87f38795a7a4a0196d7214f90ed929" }
tokio = { version = "1.11.0", features = ["macros", "rt-multi-thread"] }

[target.'cfg(windows)'.dependencies]
winreg = "0.10.1"

[dependencies.tauri]
default-features = false
# `wry` and `objc-exception` features are default, but we disable `compression` feature to avoid `zstd` crate version conflicts
features = ["api-all", "objc-exception", "system-tray", "wry"]
version = "1.0.0-rc.4"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]

[profile.dev]
opt-level = 3
