[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = [ "you" ]
license = "Apache-2.0"
repository = ""
default-run = "app"
edition = "2021"
build = "src/build.rs"

[build-dependencies]
tauri-build = { version = "1.0.0-beta.4" }

[dependencies]
anyhow = "1.0.44"
event-listener-primitives = "2.0.1"
fs2 = "0.4.3"
lazy_static = "1.4.0"
log = "0.4.14"
sc-cli = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", rev = "e6def65920d30029e42d498cb07cec5dd433b927", features = ["wasmtime"] }
sc-executor = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", rev = "e6def65920d30029e42d498cb07cec5dd433b927", features = ["wasmtime"] }
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
sp-core = { version = "5.0.0", git = "https://github.com/paritytech/substrate", rev = "e6def65920d30029e42d498cb07cec5dd433b927" }
subspace-core-primitives = { git = "https://github.com/subspace/subspace", rev = "c76d6744a17933fe82811ad809856d665869cdaa" }
subspace-farmer = { git = "https://github.com/subspace/subspace", rev = "c76d6744a17933fe82811ad809856d665869cdaa" }
subspace-node = { git = "https://github.com/subspace/subspace", rev = "c76d6744a17933fe82811ad809856d665869cdaa" }
subspace-runtime = { git = "https://github.com/subspace/subspace", rev = "c76d6744a17933fe82811ad809856d665869cdaa" }
subspace-service = { git = "https://github.com/subspace/subspace", rev = "c76d6744a17933fe82811ad809856d665869cdaa" }
subspace-solving = { git = "https://github.com/subspace/subspace", rev = "c76d6744a17933fe82811ad809856d665869cdaa" }
tiny-bip39 = "0.8.2"
tokio = { version = "1.11.0", features = ["macros", "rt-multi-thread"] }

[target.'cfg(windows)'.dependencies]
winreg = "0.10.1"

[dependencies.tauri]
version = "1.0.0-beta.8"
features = ["api-all", "system-tray"]

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
